[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/identity"
  status = 401
  force = false
  conditions = {Role = ["authenticated"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
